### ISSUE TITLE
[REQUEST] Dark Theme

### ISSUE THREAD

**Issue by Insta-Dev** [Rushor/SAI-Editor#2]
The application is amazing, but if a dark theme can be added it'd be neat!

Not sure where to insert a request, sorry if I misplaced it.

**Comment by Rushor** [comment]
i could add a grey colour around the topics

**Comment by Rushor** [comment]
added a grey version in this commit: https://github.com/Rushor/SAI-Editor/commit/328c84d85bf764f29bfd42a208a50c3f7e4eaa52 @Insta-Dev
